/* -------------------------------------------
   PRESENT SIMPLE – AFFIRMATIVE (60)
------------------------------------------- */
const PS_aff = [
  "She usually walks to school.",
  "He plays the guitar every afternoon.",
  "They enjoy quiet mornings together.",
  "My cat sleeps on my backpack.",
  "I like how this coffee smells.",
  "We live near the park.",
  "The dog understands simple commands.",
  "My brother cooks dinner on Fridays.",
  "She reads before going to bed.",
  "He often forgets his keys at home.",
  "They play football in the playground.",
  "The shop opens at nine.",
  "My sister studies French at school.",
  "He likes drawing robots.",
  "We eat lunch together on weekends.",
  "The train leaves at eight.",
  "She loves rainy days.",
  "They walk their dog every evening.",
  "He drinks tea in the morning.",
  "My parents cook dinner together.",
  "The sun rises in the east.",
  "Birds fly in the sky.",
  "She enjoys quiet music.",
  "He plays chess with his dad.",
  "We visit our grandparents on Sundays.",
  "They clean their room every Saturday.",
  "My cousin lives in Madrid.",
  "She likes chocolate ice cream.",
  "He reads comics after school.",
  "We watch movies on Fridays.",
  "They help their neighbours sometimes.",
  "My dog waits for me at the door.",
  "She sings in the school choir.",
  "He practices basketball every day.",
  "We talk during lunch break.",
  "They share snacks in class.",
  "My aunt teaches English.",
  "She paints beautiful pictures.",
  "He listens to rock music.",
  "We enjoy sunny afternoons.",
  "They laugh a lot together.",
  "My friend plays the piano.",
  "She writes stories in her notebook.",
  "He collects stickers.",
  "We celebrate birthdays at home.",
  "They travel during holidays.",
  "My grandma bakes amazing cakes.",
  "She waters the plants every morning.",
  "He feeds the cat before school.",
  "We take the bus to class.",
  "They study in the library.",
  "My uncle works in a hospital.",
  "She keeps her room tidy.",
  "He plays video games after homework.",
  "We read books in English class.",
  "They enjoy long walks.",
  "My neighbour grows tomatoes.",
  "She practices yoga on weekends.",
  "He likes science experiments."
];


/* -------------------------------------------
   PRESENT SIMPLE – NEGATIVE (60)
------------------------------------------- */
const PS_neg = [
  "She doesn’t like cold pizza.",
  "They don’t study on Sundays.",
  "He does not enjoy long movies.",
  "I don’t drink soda anymore.",
  "The cat doesn’t sleep in its bed.",
  "We don’t walk to school when it rains.",
  "She does not play video games.",
  "They don’t eat meat.",
  "He doesn’t listen to loud music.",
  "I do not watch TV in the morning.",
  "She doesn’t enjoy crowded places.",
  "They don’t visit the museum often.",
  "He does not like spicy food.",
  "We don’t clean the house on Fridays.",
  "My dog doesn’t bark at night.",
  "She doesn’t drink coffee.",
  "He doesn’t wake up early.",
  "They don’t play tennis.",
  "We don’t buy snacks at school.",
  "My brother doesn’t study French.",
  "She does not like horror movies.",
  "He doesn’t eat vegetables.",
  "They don’t walk their dog every day.",
  "We don’t travel in winter.",
  "My parents don’t watch reality shows.",
  "She doesn’t read newspapers.",
  "He does not enjoy swimming.",
  "They don’t help with chores sometimes.",
  "We don’t use our phones in class.",
  "My cousin doesn’t live nearby.",
  "She doesn’t like loud noises.",
  "He doesn’t play the violin.",
  "They don’t drink tea.",
  "We don’t stay up late.",
  "My aunt doesn’t teach maths.",
  "She doesn’t paint landscapes.",
  "He does not listen to jazz.",
  "They don’t laugh at bad jokes.",
  "We don’t celebrate Halloween.",
  "My friend doesn’t play football.",
  "She doesn’t write poems.",
  "He doesn’t collect stamps.",
  "They don’t travel by train.",
  "We don’t bake cakes at home.",
  "My grandma doesn’t use a smartphone.",
  "She doesn’t water the plants daily.",
  "He doesn’t feed the dog in the morning.",
  "They don’t study in the afternoon.",
  "We don’t take the metro.",
  "My uncle doesn’t work on weekends.",
  "She doesn’t keep old photos.",
  "He doesn’t play board games.",
  "They don’t enjoy long walks.",
  "We don’t read magazines.",
  "My neighbour doesn’t grow flowers.",
  "She doesn’t practice yoga.",
  "He doesn’t like science fiction.",
  "They don’t eat breakfast early.",
  "We don’t talk during exams."
];
/* -------------------------------------------
   PRESENT SIMPLE – INTERROGATIVE (60)
------------------------------------------- */
const PS_int = [
  "Do you like spicy food?",
  "Does she play the violin?",
  "Do they live near here?",
  "Does he enjoy swimming?",
  "Do we have class today?",
  "Does your dog understand Spanish?",
  "Do you read before bed?",
  "Does she drink coffee?",
  "Do they visit their grandparents often?",
  "Does he walk to school?",
  "Do you enjoy quiet mornings?",
  "Does she study French?",
  "Do they play football?",
  "Does he clean his room?",
  "Do we eat lunch together?",
  "Does your sister like music?",
  "Do you watch movies on Fridays?",
  "Does he read comics?",
  "Do they help their neighbours?",
  "Does she cook dinner?",
  "Do you travel in summer?",
  "Does he drink tea?",
  "Do they walk their dog?",
  "Does she enjoy rainy days?",
  "Do you like chocolate?",
  "Does he play chess?",
  "Do they study in the library?",
  "Does she wake up early?",
  "Do you speak English?",
  "Does he like drawing?",
  "Do they clean the house?",
  "Does she visit her grandparents?",
  "Do you listen to music?",
  "Does he enjoy science?",
  "Do they share snacks?",
  "Does she write stories?",
  "Do you play video games?",
  "Does he like animals?",
  "Do they celebrate birthdays?",
  "Does she paint pictures?",
  "Do you enjoy long walks?",
  "Does he collect stickers?",
  "Do they travel by train?",
  "Does she water the plants?",
  "Do you take the bus?",
  "Does he feed the cat?",
  "Do they study in the afternoon?",
  "Does she keep her room tidy?",
  "Do you read books in English?",
  "Does he like science fiction?",
  "Do they eat breakfast early?",
  "Does she practice yoga?",
  "Do you enjoy sunny days?",
  "Does he play the piano?",
  "Do they laugh a lot?",
  "Does she like ice cream?",
  "Do you enjoy art?",
  "Does he watch TV?",
  "Do they live nearby?",
  "Does she like sports?"
];


/* -------------------------------------------
   PRESENT CONTINUOUS – AFFIRMATIVE (60)
------------------------------------------- */
const PC_aff = [
  "She’s studying English right now.",
  "They are cooking dinner together.",
  "He’s drawing a robot at the moment.",
  "I’m listening to music.",
  "We’re walking to the bus stop.",
  "She is writing a message.",
  "They’re laughing about something.",
  "He is fixing his bike.",
  "I’m cleaning my room.",
  "We are having lunch now.",
  "She’s talking on the phone.",
  "They are running in the playground.",
  "He’s playing football outside.",
  "I’m doing my homework.",
  "We’re watching a movie.",
  "She is reading a book.",
  "They’re waiting for the bus.",
  "He is opening the window.",
  "I’m drinking water.",
  "We are studying together.",
  "She’s wearing a blue jacket.",
  "They are singing a song.",
  "He’s washing the dishes.",
  "I’m writing an email.",
  "We’re preparing dinner.",
  "She is drawing a flower.",
  "They’re building a sandcastle.",
  "He is learning new vocabulary.",
  "I’m stretching my legs.",
  "We are packing our bags.",
  "She’s feeding the cat.",
  "They are cleaning the classroom.",
  "He’s checking his phone.",
  "I’m practicing English.",
  "We’re choosing a movie.",
  "She is opening her notebook.",
  "They’re playing a board game.",
  "He is brushing his hair.",
  "I’m tying my shoes.",
  "We are planning a trip.",
  "She’s baking cookies.",
  "They are fixing the table.",
  "He’s carrying a backpack.",
  "I’m looking for my keys.",
  "We’re eating breakfast.",
  "She is listening to a podcast.",
  "They’re painting a mural.",
  "He is watering the plants.",
  "I’m sending a message.",
  "We are checking the answers.",
  "She’s choosing a song.",
  "They are opening their books.",
  "He’s taking notes.",
  "I’m waiting for my friend.",
  "We’re walking home.",
  "She is practicing the piano.",
  "They’re organizing their desks.",
  "He is closing the door.",
  "I’m reading the instructions."
];/* -------------------------------------------
   PRESENT SIMPLE – INTERROGATIVE (60)
------------------------------------------- */
const PS_int = [
  "Do you like spicy food?",
  "Does she play the violin?",
  "Do they live near here?",
  "Does he enjoy swimming?",
  "Do we have class today?",
  "Does your dog understand Spanish?",
  "Do you read before bed?",
  "Does she drink coffee?",
  "Do they visit their grandparents often?",
  "Does he walk to school?",
  "Do you enjoy quiet mornings?",
  "Does she study French?",
  "Do they play football?",
  "Does he clean his room?",
  "Do we eat lunch together?",
  "Does your sister like music?",
  "Do you watch movies on Fridays?",
  "Does he read comics?",
  "Do they help their neighbours?",
  "Does she cook dinner?",
  "Do you travel in summer?",
  "Does he drink tea?",
  "Do they walk their dog?",
  "Does she enjoy rainy days?",
  "Do you like chocolate?",
  "Does he play chess?",
  "Do they study in the library?",
  "Does she wake up early?",
  "Do you speak English?",
  "Does he like drawing?",
  "Do they clean the house?",
  "Does she visit her grandparents?",
  "Do you listen to music?",
  "Does he enjoy science?",
  "Do they share snacks?",
  "Does she write stories?",
  "Do you play video games?",
  "Does he like animals?",
  "Do they celebrate birthdays?",
  "Does she paint pictures?",
  "Do you enjoy long walks?",
  "Does he collect stickers?",
  "Do they travel by train?",
  "Does she water the plants?",
  "Do you take the bus?",
  "Does he feed the cat?",
  "Do they study in the afternoon?",
  "Does she keep her room tidy?",
  "Do you read books in English?",
  "Does he like science fiction?",
  "Do they eat breakfast early?",
  "Does she practice yoga?",
  "Do you enjoy sunny days?",
  "Does he play the piano?",
  "Do they laugh a lot?",
  "Does she like ice cream?",
  "Do you enjoy art?",
  "Does he watch TV?",
  "Do they live nearby?",
  "Does she like sports?"
];


/* -------------------------------------------
   PRESENT CONTINUOUS – AFFIRMATIVE (60)
------------------------------------------- */
const PC_aff = [
  "She’s studying English right now.",
  "They are cooking dinner together.",
  "He’s drawing a robot at the moment.",
  "I’m listening to music.",
  "We’re walking to the bus stop.",
  "She is writing a message.",
  "They’re laughing about something.",
  "He is fixing his bike.",
  "I’m cleaning my room.",
  "We are having lunch now.",
  "She’s talking on the phone.",
  "They are running in the playground.",
  "He’s playing football outside.",
  "I’m doing my homework.",
  "We’re watching a movie.",
  "She is reading a book.",
  "They’re waiting for the bus.",
  "He is opening the window.",
  "I’m drinking water.",
  "We are studying together.",
  "She’s wearing a blue jacket.",
  "They are singing a song.",
  "He’s washing the dishes.",
  "I’m writing an email.",
  "We’re preparing dinner.",
  "She is drawing a flower.",
  "They’re building a sandcastle.",
  "He is learning new vocabulary.",
  "I’m stretching my legs.",
  "We are packing our bags.",
  "She’s feeding the cat.",
  "They are cleaning the classroom.",
  "He’s checking his phone.",
  "I’m practicing English.",
  "We’re choosing a movie.",
  "She is opening her notebook.",
  "They’re playing a board game.",
  "He is brushing his hair.",
  "I’m tying my shoes.",
  "We are planning a trip.",
  "She’s baking cookies.",
  "They are fixing the table.",
  "He’s carrying a backpack.",
  "I’m looking for my keys.",
  "We’re eating breakfast.",
  "She is listening to a podcast.",
  "They’re painting a mural.",
  "He is watering the plants.",
  "I’m sending a message.",
  "We are checking the answers.",
  "She’s choosing a song.",
  "They are opening their books.",
  "He’s taking notes.",
  "I’m waiting for my friend.",
  "We’re walking home.",
  "She is practicing the piano.",
  "They’re organizing their desks.",
  "He is closing the door.",
  "I’m reading the instructions."
];/* -------------------------------------------
   PRESENT SIMPLE – INTERROGATIVE (60)
------------------------------------------- */
const PS_int = [
  "Do you like spicy food?",
  "Does she play the violin?",
  "Do they live near here?",
  "Does he enjoy swimming?",
  "Do we have class today?",
  "Does your dog understand Spanish?",
  "Do you read before bed?",
  "Does she drink coffee?",
  "Do they visit their grandparents often?",
  "Does he walk to school?",
  "Do you enjoy quiet mornings?",
  "Does she study French?",
  "Do they play football?",
  "Does he clean his room?",
  "Do we eat lunch together?",
  "Does your sister like music?",
  "Do you watch movies on Fridays?",
  "Does he read comics?",
  "Do they help their neighbours?",
  "Does she cook dinner?",
  "Do you travel in summer?",
  "Does he drink tea?",
  "Do they walk their dog?",
  "Does she enjoy rainy days?",
  "Do you like chocolate?",
  "Does he play chess?",
  "Do they study in the library?",
  "Does she wake up early?",
  "Do you speak English?",
  "Does he like drawing?",
  "Do they clean the house?",
  "Does she visit her grandparents?",
  "Do you listen to music?",
  "Does he enjoy science?",
  "Do they share snacks?",
  "Does she write stories?",
  "Do you play video games?",
  "Does he like animals?",
  "Do they celebrate birthdays?",
  "Does she paint pictures?",
  "Do you enjoy long walks?",
  "Does he collect stickers?",
  "Do they travel by train?",
  "Does she water the plants?",
  "Do you take the bus?",
  "Does he feed the cat?",
  "Do they study in the afternoon?",
  "Does she keep her room tidy?",
  "Do you read books in English?",
  "Does he like science fiction?",
  "Do they eat breakfast early?",
  "Does she practice yoga?",
  "Do you enjoy sunny days?",
  "Does he play the piano?",
  "Do they laugh a lot?",
  "Does she like ice cream?",
  "Do you enjoy art?",
  "Does he watch TV?",
  "Do they live nearby?",
  "Does she like sports?"
];


/* -------------------------------------------
   PRESENT CONTINUOUS – AFFIRMATIVE (60)
------------------------------------------- */
const PC_aff = [
  "She’s studying English right now.",
  "They are cooking dinner together.",
  "He’s drawing a robot at the moment.",
  "I’m listening to music.",
  "We’re walking to the bus stop.",
  "She is writing a message.",
  "They’re laughing about something.",
  "He is fixing his bike.",
  "I’m cleaning my room.",
  "We are having lunch now.",
  "She’s talking on the phone.",
  "They are running in the playground.",
  "He’s playing football outside.",
  "I’m doing my homework.",
  "We’re watching a movie.",
  "She is reading a book.",
  "They’re waiting for the bus.",
  "He is opening the window.",
  "I’m drinking water.",
  "We are studying together.",
  "She’s wearing a blue jacket.",
  "They are singing a song.",
  "He’s washing the dishes.",
  "I’m writing an email.",
  "We’re preparing dinner.",
  "She is drawing a flower.",
  "They’re building a sandcastle.",
  "He is learning new vocabulary.",
  "I’m stretching my legs.",
  "We are packing our bags.",
  "She’s feeding the cat.",
  "They are cleaning the classroom.",
  "He’s checking his phone.",
  "I’m practicing English.",
  "We’re choosing a movie.",
  "She is opening her notebook.",
  "They’re playing a board game.",
  "He is brushing his hair.",
  "I’m tying my shoes.",
  "We are planning a trip.",
  "She’s baking cookies.",
  "They are fixing the table.",
  "He’s carrying a backpack.",
  "I’m looking for my keys.",
  "We’re eating breakfast.",
  "She is listening to a podcast.",
  "They’re painting a mural.",
  "He is watering the plants.",
  "I’m sending a message.",
  "We are checking the answers.",
  "She’s choosing a song.",
  "They are opening their books.",
  "He’s taking notes.",
  "I’m waiting for my friend.",
  "We’re walking home.",
  "She is practicing the piano.",
  "They’re organizing their desks.",
  "He is closing the door.",
  "I’m reading the instructions."
];/* -------------------------------------------
   PRESENT CONTINUOUS – NEGATIVE (60)
------------------------------------------- */
const PC_neg = [
  "She isn’t studying today.",
  "They aren’t watching TV right now.",
  "He is not working at the moment.",
  "I’m not cooking dinner.",
  "We aren’t walking anywhere.",
  "She is not listening to music.",
  "They aren’t doing their homework.",
  "He isn’t coming to class today.",
  "I am not wearing a jacket.",
  "We’re not having lunch yet.",
  "She isn’t talking on the phone.",
  "They aren’t running in the playground.",
  "He is not playing football.",
  "I’m not doing my homework.",
  "We aren’t watching a movie.",
  "She is not reading a book.",
  "They aren’t waiting for the bus.",
  "He isn’t opening the window.",
  "I’m not drinking water.",
  "We are not studying together.",
  "She isn’t wearing a blue jacket.",
  "They aren’t singing a song.",
  "He is not washing the dishes.",
  "I’m not writing an email.",
  "We aren’t preparing dinner.",
  "She is not drawing a flower.",
  "They aren’t building a sandcastle.",
  "He isn’t learning new vocabulary.",
  "I’m not stretching my legs.",
  "We are not packing our bags.",
  "She isn’t feeding the cat.",
  "They aren’t cleaning the classroom.",
  "He is not checking his phone.",
  "I’m not practicing English.",
  "We aren’t choosing a movie.",
  "She is not opening her notebook.",
  "They aren’t playing a board game.",
  "He isn’t brushing his hair.",
  "I’m not tying my shoes.",
  "We are not planning a trip.",
  "She isn’t baking cookies.",
  "They aren’t fixing the table.",
  "He is not carrying a backpack.",
  "I’m not looking for my keys.",
  "We aren’t eating breakfast.",
  "She is not listening to a podcast.",
  "They aren’t painting a mural.",
  "He isn’t watering the plants.",
  "I’m not sending a message.",
  "We are not checking the answers.",
  "She isn’t choosing a song.",
  "They aren’t opening their books.",
  "He is not taking notes.",
  "I’m not waiting for my friend.",
  "We aren’t walking home.",
  "She is not practicing the piano.",
  "They aren’t organizing their desks.",
  "He isn’t closing the door.",
  "I’m not reading the instructions.",
  "We are not talking right now."
];


/* -------------------------------------------
   PRESENT CONTINUOUS – INTERROGATIVE (60)
------------------------------------------- */
const PC_int = [
  "Are you studying right now?",
  "Is she doing her homework?",
  "Are they coming to the party?",
  "Is he working today?",
  "Are we walking too fast?",
  "Is your cat sleeping on your laptop again?",
  "Are you listening to me?",
  "Is she cooking dinner at the moment?",
  "Are they waiting for the bus?",
  "Is he wearing his new jacket?",
  "Are you reading a book?",
  "Is she talking on the phone?",
  "Are they running outside?",
  "Is he playing football?",
  "Are we watching a movie?",
  "Is your sister studying?",
  "Are you drinking water?",
  "Is he opening the window?",
  "Are they singing a song?",
  "Is she writing a message?",
  "Are you doing your homework?",
  "Is he washing the dishes?",
  "Are they building something?",
  "Is she drawing a picture?",
  "Are you practicing English?",
  "Is he checking his phone?",
  "Are they cleaning the classroom?",
  "Is she wearing a red jacket?",
  "Are you waiting for someone?",
  "Is he learning new vocabulary?",
  "Are they preparing lunch?",
  "Is she feeding the cat?",
  "Are you choosing a movie?",
  "Is he brushing his hair?",
  "Are they fixing the table?",
  "Is she baking cookies?",
  "Are you looking for your keys?",
  "Is he carrying a backpack?",
  "Are they painting a mural?",
  "Is she listening to a podcast?",
  "Are you sending a message?",
  "Is he taking notes?",
  "Are they opening their books?",
  "Is she practicing the piano?",
  "Are you walking home?",
  "Is he closing the door?",
  "Are they organizing their desks?",
  "Is she reading the instructions?",
  "Are you planning a trip?",
  "Is he stretching his legs?",
  "Are they packing their bags?",
  "Is she watering the plants?",
  "Are you eating breakfast?",
  "Is he writing an email?",
  "Are they laughing about something?",
  "Is she choosing a song?",
  "Are you checking the answers?",
  "Is he fixing his bike?",
  "Are they playing a board game?",
  "Is she opening her notebook?"
];
